-- book: 도서정보, author: 저자 정보, book_sales: 각 도서의 날짜 별 판매량
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) as TOTAL_SALES
FROM BOOK
INNER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
INNER JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE date_format(BOOK_SALES.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID asc, CATEGORY desc;