-- PRODUCT, OFFLINE_SALE 
SELECT p.PRODUCT_CODE, SUM(p.PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT p
INNER JOIN OFFLINE_SALE off
ON p.PRODUCT_ID = off.PRODUCT_ID 
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;